name: Print GitHub Secret

on:
  push:
    branches: [ main ]

jobs:
  print-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Python script to print secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          python3 print_secret.py
